# -*- mode:org -*-
#+TITLE: bear
#+STARTUP: indent
#+OPTIONS: toc:nil
x-callback-url wrapper for bear on OSX
** Overview :TOC:
- [[#installation][Installation]]
- [[#usage][Usage]]
  - [[#org-mode][org-mode]]
- [[#limitations][Limitations]]
- [[#extending][Extending]]
- [[#implementation][Implementation]]

* Installation
You will need Emacs 24+, `make` and [Cask](https://github.com/cask/cask) to
build the project.

#+BEGIN_SRC shell
    cd bear
    make && make install
#+END_SRC
* Usage

Set your notes directory
#+BEGIN_SRC elisp
M-x customize-group bear
#+END_SRC

To create a note:
#+BEGIN_SRC elisp
M-x bear:create-note
#+END_SRC

Which will prompt you for a
- note title
- tag string (eg. top-level/sub-heading1-sub-heading2)

Now you're in a markdown buffer, once done editing:

#+BEGIN_SRC elisp
C-c C-c
#+END_SRC

This /should/ pop open Bear.app with the note you have just created there
** org-mode
#+BEGIN_SRC elisp
M-x bear:create-note-org
#+END_SRC

Which will prompt you for a
- note title
- tag string (eg. top-level/sub-heading1-sub-heading2)

Now you're in a org buffer, once done editing:
#+BEGIN_SRC elisp
C-c C
#+END_SRC

review markdown formatting and push to bear as before with
#+BEGIN_SRC elisp
C-c C-c
#+END_SRC

* Limitations
I indiscriminately convert all single quotes to double quotes to make
this work.  I imagine there are quoting bugs galore but so far haven't
run in into anything as my notes have simple title and content by and large.
* Extending
Add more functions and add them to the minor mode keybinding
* [[file:bear.el][Implementation]]
